beeware/gbulb

gbulb/glib_events.py, gbulb/gtk.py, gbulb/utils.py, setup.py, tests/test_glib_events.py, tests/test_utils.py
Nobody wants to import Gtk in non-GUI programs just to check it's there.
Move Gtk-dependent classes into a separate module and put the user in control. Don't play games with Gtk availability at all. Don't hide whatever exception Gtk import might throw.
Bump version to 0.2 due to API changes.
=> Avoid importing Gtk unnecessarily

examples/test-gtk.py, tests/test_glib_events.py, tests/test_gtk.py, tests/test_utils.py, tests/utils.py
Some missing bits and organizing of gtk tests.
Also:
- `gtk_policy` and `gtk_loop` fixtures are moved to tests/utils.py to live close to their glib counterparts
- `gtk_loop` is changed a bit to follow the way `glib_loop` was written - please check if that's OK as my pytest-fu is quite weak.
=> Follow-up to Gtk-related changes

gbulb/glib_events.py
This fixes a race condition leading to a memory leak. The source can be
executed even before the handle was added to the handlers set. In that
case, it is only added after being run and never removed.
Fix this problem by adding it to the handlers set before attaching the
source.
=> Fix race condition during Handle creation.

gbulb/glib_events.py, gbulb/transports.py, tests/test_glib_events.py
As can be seen from the list of known issues below, this still needs some work to be really usable, but the initial implementation is done and if you have any feedback or suggestions about it I'd be happy to discuss that with you and incorporate any necessary changes.
As you study the code you'll probably notice that this is a mostly rewrite of the library, implementing a full-fledged event loop (similar to `asyncio`'s `SelectorEventLoop` and `ProactorEventLoop`) on top of `base_events.BaseEventLoop` instead of somehow trying to use `SelectorEventLoop` for this. This IMHO makes for more readable and stable code, because we're simply implementing the well defined interfaces from the `BaseEventLoop` instead of monkey-patching `SelectorEventLoop` to fit our needs.
Known issues:
- ~TCP …
=> Windows support

.drone.yml, gbulb/glib_events.py, setup.py
This pull request fixes a syntax error when running GBulb in Python 3.5+. The reason the syntax was changed was that asyncio.async had to be replaced with asyncio.ensure_future because in Python >= 3.5, [async was made keyword](https://www.python.org/dev/peps/pep-0492/#backwards-compatibility)
Signed-off-by: Dan Yeaw <dan@yeaw.me>
=> Fix syntax error for Python 3.5+ by replacing tasks.async

changes/56.bugfix.rst, src/gbulb/transports.py
Corrects the import path for `asyncio.InvalidStateError`
=> Fixes #56 - Correct import path for InvalidStateError

src/gbulb/transports.py
Merely detaching leads to the socket still being open, and thus behaves
differently from Python's asyncio where .close() on the transport also
closes the socket.
---
When calling `.close()` on a TCP socket, unlike in upstream asyncio, this does not cause the TCP connection to be closed, but merely leaks the file descriptor (which is what `.detach()` on a socket is described to do in the Python documentation).
This is precisly a revert of f900d4121a063f969b400e14a3c003d915a1404d  -- @dob3001 might have ideas why this is a bad idea, or check against the original use case. I couldn't do that because #47 contains no further explanations. Possibly, the file descriptor was still used in earlier versions of gbulb by something that'd close it, and now that other component was changed.
The problem …
=> transports: Close socket when closing the transport

.github/workflows/ci.yml, changes/61.feature.rst, setup.cfg, src/gbulb/glib_events.py, tests/test_utils.py
Updates to support Python 3.11 and 3.12:
* Adds the now-required SSL timeout parameters
* Modifies tests to use explicit tasks, rather than coroutines.
Fixes #61.
=> Add support for Python 3.11/3.12

.github/workflows/ci.yml, changes/59.bugfix.rst, src/gbulb/glib_events.py, src/gbulb/gtk.py
This caused “fun” migration of all scheduled callbacks between event loop instances with equally “fun” to debug asyncio low-level exceptions when using multi-threading with several concurrently running event loops.
It is completely unclear to the author of this change why the original change causes this breakage was introduced in 2015 in commit fde03cde in the first place. Perhaps the intention was merely to use the GLib default main context on the default main loop instance? Or perhaps its supposed to be shared between all instances of the main loop on the UI/main thread (some kind of recursion workaround maybe)?
=> Prevent the GTK event loop from reusing the default GLib main context for every instance

.github/workflows/ci.yml, .github/workflows/pre-commit-update.yml, .pre-commit-config.yaml, changes/64.misc.rst
~~ Waiting on `flake8-eradicate` to be updated for `flake8>=6` ~~
~~- https://github.com/wemake-services/flake8-eradicate/pull/271~~
Updated `pre-commit` hooks and dropped support for `flake8-eradicate` due to extended incompatibility with `flake8==6.0.0`.
See beeware/.github#6 for details.
=> Add GitHub workflow to keep `pre-commit` hooks up-to-date

changes/61.feature.rst, changes/69.feature.rst, src/gbulb/utils.py, tests/test_utils.py
Python 3.12a3 finalised the change to `get_child_loop()`; as a result, an explicit `new_child_loop()` API is required.
=> Add an explicit new_child_loop API

.github/workflows/publish.yml, changes/80.misc.rst, tox.ini
Adds the `id-token: write` permission to the publishing workflow to take advantage of trusted publishers. Also removes the `publish` tox task since it is no longer used.
Related to: https://github.com/beeware/beeware/issues/219
=> Use trusted publisher in publishing workflow

.pre-commit-config.yaml, changes/90.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.4.0 to v3.6.0 and ran the update against the repo.
=> Bump pyupgrade from v3.4.0 to v3.6.0

.pre-commit-config.yaml, changes/91.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.6.0 to v3.7.0 and ran the update against the repo.
=> Bump pyupgrade from v3.6.0 to v3.7.0

.pre-commit-config.yaml, changes/92.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.7.0 to v3.8.0 and ran the update against the repo.
=> Bump pyupgrade from v3.7.0 to v3.8.0

.github/workflows/ci.yml, .github/workflows/publish.yml, changes/93.misc.rst, setup.cfg, tox.ini
- Stops installing `python3-gi` in CI; installing `PyGObject` from PyPI will handle this dependency
=> Refine Linux requirements for CI

.pre-commit-config.yaml, changes/94.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.8.0 to v3.9.0 and ran the update against the repo.
=> Bump pyupgrade from v3.8.0 to v3.9.0

.pre-commit-config.yaml, changes/95.misc.rst
Bumps `pre-commit` hook for `black` from 23.3.0 to 23.7.0 and ran the update against the repo.
=> Bump black from 23.3.0 to 23.7.0

.pre-commit-config.yaml, changes/97.misc.rst
Bumps `pre-commit` hook for `flake8` from 6.0.0 to 6.1.0 and ran the update against the repo.
=> Bump flake8 from 6.0.0 to 6.1.0

.pre-commit-config.yaml, changes/98.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.9.0 to v3.10.1 and ran the update against the repo.
=> Bump pyupgrade from v3.9.0 to v3.10.1

.pre-commit-config.yaml, changes/100.misc.rst
Bumps `pre-commit` hook for `black` from 23.7.0 to 23.9.0 and ran the update against the repo.
=> Bump black from 23.7.0 to 23.9.0

changes/78.bugfix.rst, tests/test_utils.py
Python 3.12 removed support for using generators as co-routines. The test suite contained a couple of instances of this; this PR removes those usages.
No APIs have been changed, so generators should continue to work a co-routines on Python3.11; however, it would be generally advisable to update any existing code that is relying on this.
Fixes #78.
=> Updated test suite to remove use of generators as co-routines.

.pre-commit-config.yaml, changes/103.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.10.1 to v3.11.0 and ran the update against the repo.
=> Bump pyupgrade from v3.10.1 to v3.11.0

.pre-commit-config.yaml, changes/104.misc.rst
Bumps `pre-commit` hook for `black` from 23.9.0 to 23.9.1 and ran the update against the repo.
=> Bump black from 23.9.0 to 23.9.1

.pre-commit-config.yaml, changes/105.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.11.0 to v3.13.0 and ran the update against the repo.
=> Bump pyupgrade from v3.11.0 to v3.13.0

.pre-commit-config.yaml, changes/107.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.13.0 to v3.15.0 and ran the update against the repo.
=> Bump pyupgrade from v3.13.0 to v3.15.0

.pre-commit-config.yaml, changes/108.misc.rst
Bumps `pre-commit` hook for `pre-commit-hooks` from v4.4.0 to v4.5.0 and ran the update against the repo.
=> Bump pre-commit-hooks from v4.4.0 to v4.5.0

.pre-commit-config.yaml, changes/112.misc.rst
Bumps `pre-commit` hook for `black` from 23.9.1 to 23.10.0 and ran the update against the repo.
=> Bump black from 23.9.1 to 23.10.0

.pre-commit-config.yaml, changes/114.misc.rst
Bumps `pre-commit` hook for `black` from 23.10.0 to 23.10.1 and ran the update against the repo.
=> Bump black from 23.10.0 to 23.10.1

.pre-commit-config.yaml, changes/115.misc.rst
Bumps `pre-commit` hook for `black` from 23.10.1 to 23.11.0 and ran the update against the repo.
=> Bump black from 23.10.1 to 23.11.0

.pre-commit-config.yaml, changes/119.misc.rst
Bumps `pre-commit` hook for `isort` from 5.12.0 to 5.13.0 and ran the update against the repo.
=> Bump isort from 5.12.0 to 5.13.0

.pre-commit-config.yaml, changes/121.misc.rst
Bumps `pre-commit` hook for `isort` from 5.13.0 to 5.13.2 and ran the update against the repo.
=> Bump isort from 5.13.0 to 5.13.2

.pre-commit-config.yaml, changes/120.misc.rst
Bumps `pre-commit` hook for `black` from 23.11.0 to 23.12.0 and ran the update against the repo.
=> Bump black from 23.11.0 to 23.12.0

.pre-commit-config.yaml, changes/122.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 23.12.0 to 23.12.1 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 23.12.0 to 23.12.1

.pre-commit-config.yaml, changes/123.misc.rst
Bumps `pre-commit` hook for `flake8` from 6.1.0 to 7.0.0 and ran the update against the repo.
=> Bump flake8 from 6.1.0 to 7.0.0

.pre-commit-config.yaml, changes/124.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 23.12.1 to 24.1.1 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 23.12.1 to 24.1.1

.pre-commit-config.yaml, changes/126.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.1.1 to 24.2.0 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 24.1.1 to 24.2.0

.pre-commit-config.yaml, changes/125.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.15.0 to v3.15.1 and ran the update against the repo.
=> Bump pyupgrade from v3.15.0 to v3.15.1

.pre-commit-config.yaml, changes/127.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.2.0 to 24.3.0 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 24.2.0 to 24.3.0

.pre-commit-config.yaml, changes/129.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.15.1 to v3.15.2 and ran the update against the repo.
=> Bump pyupgrade from v3.15.1 to v3.15.2

.pre-commit-config.yaml, changes/131.misc.rst
Bumps `pre-commit` hook for `pre-commit-hooks` from v4.5.0 to v4.6.0 and ran the update against the repo.
=> Bump pre-commit-hooks from v4.5.0 to v4.6.0

.pre-commit-config.yaml, changes/132.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.3.0 to 24.4.0 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 24.3.0 to 24.4.0

.pre-commit-config.yaml, changes/134.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.4.0 to 24.4.2 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 24.4.0 to 24.4.2

README.rst, changes/136.doc.rst
- See https://github.com/github/markup/issues/1801
- See https://github.com/beeware/toga/issues/2491
- Live version: https://github.com/rmartin16/gbulb/tree/readme-badges
=> Ensure README badges are aligned instead of stacked

.github/workflows/config-file-deps-bump.yml, changes/146.misc.rst, pyproject.toml
Adds a config file updating workflow.
=> Add workflow for config file bumps

.pre-commit-config.yaml, changes/144.misc.rst
Bumps `pre-commit` hook for `codespell` from v2.2.6 to v2.3.0 and ran the update against the repo.
=> Bump codespell from v2.2.6 to v2.3.0

.github/workflows/ci.yml, changes/148.misc.rst, tox.ini
- Implement https://github.com/beeware/.github/pull/137
- Run `check-wheel-contents` during `tox -e package`
- Remove `tox -e package` target
- The release workflow here is significantly different than other repos so I didn't update it to support attestation.
=> Use new create package action

.pre-commit-config.yaml, changes/150.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.15.2 to v3.16.0 and ran the update against the repo.
=> Bump pyupgrade from v3.15.2 to v3.16.0

.pre-commit-config.yaml, changes/154.misc.rst
Bumps `pre-commit` hook for `flake8` from 7.0.0 to 7.1.0 and ran the update against the repo.
=> Bump flake8 from 7.0.0 to 7.1.0

.pre-commit-config.yaml, changes/166.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.16.0 to v3.17.0 and ran the update against the repo.
=> Bump pyupgrade from v3.16.0 to v3.17.0

.pre-commit-config.yaml, changes/173.misc.rst
Bumps `pre-commit` hook for `flake8` from 7.1.0 to 7.1.1 and ran the update against the repo.
=> Bump flake8 from 7.1.0 to 7.1.1

.pre-commit-config.yaml, changes/175.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.4.2 to 24.8.0 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 24.4.2 to 24.8.0

changes/176.bugfix.rst, src/gbulb/glib_events.py, tests/test_glib_events.py
_UnixSelectorEventLoop in Python 3.13 expect _unix_server_sockets dict, add one. It's later used (among others) in _stop_serving(), but not in close() directly, so just adding attribute is enough.
The related CPython change: 74b868f636a "gh-111246: Remove listening Unix socket on close (#111483)"
=> Fix compatibility with Python 3.13

changes/179.bugfix.rst, src/gbulb/transports.py
Fixes: 74a3ec4 "Add support for driving `BufferedProtocol` instances using `sock_recv_into`"
=> Change one remaining _buffer_empty_callbacks to _drained_callbacks
